config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :eats

  root "eats#index"

end

app/models/eat.rb
class Eat < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :eats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eats_controller.rb
class EatsController < ApplicationController
  before_action :find_eat, only: [:show, :destroy, :edit, :update]

  def index
    @eats = Eat.all.order("created_at DESC")
  end

  def create
    @eat = current_user.eats.bulid(eat_params)
    if @eat.save
      redirect_to @eat, notice: "Eat is ready for Mmm..."
    else 
      render 'new'
    end
  end

  def new
    @eat = current_user.eats.bulid
  end

  def show
  end

  def update 
    if @eat.update(eat_params)
      redirect_to @eat, notice: "Eat was updated"
    else 
      render 'edit'
    end
  end

  def destroy
    @eat.destroy
    redirect_to root_path, notice: "Eat was deleted"
  end

  def edit
  end 

  private 

  def eat_params
    params.require(:eat).permit(:title, :description)
  end

  def find_eat
    @eat = Eat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eats_helper.rb
module EatsHelper
end

app/views/eats/_form.html.haml
= simple_form_for @eat, html: {multipart: true} do |f|
	- if @eat.errors.any?
		#errors
			%h2
				=pluralize(@eat.errors.count, "error")
				prevented this Eat from saving
			%ul
				-@eat.errors.full_messages.each do |msg|
					%li = msg

	.form-group
		= f.input :title, input_html: {class: 'form-control'}

	.form-group
		= f.input :description, input_html: {class: 'form-control'}

	= f.button :submit, class: "btn btn-primary"

app/views/eats/edit.html.haml
%h1 Edit Eat

= render 'form'

= link_to "Back", root_path

app/views/eats/index.html.haml
%h1 List all Eats
= link_to "New Eat", new_eat_path
- @eats.each do |f|
	%li
		= f.title
		= f.description
		= link_to "Show", f
		= link_to "Edit", edit_eat_path(f)
		= link_to "Delete", f, method: :delete, data: {confirm: "Are you sure?"}

app/views/eats/new.html.haml
%h1 New Eats

= render 'form'

= link_to "Back", root_path

app/views/eats/show.html.haml
%h2=@eat.title
%p=@eat.description
%p
Eat was sended by 
=@eat.user.email

= link_to "Back", root_path
= link_to "Edit", edit_eat_path(@eat)
= link_to "Delete", @eat, method: :delete, data: {confirm: "Are you sure?"}

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title EatMe
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags
%body
	- flash.each do |name, msg|
		= content_tag :div, msg, class: "alert alert-info"
	= yield